title: Argument Injection Vectors

baseurl: /argument-injection-vectors

collections:
  binaries:
    output: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - _site

permalink: pretty

defaults:
  - scope:
      path: '_binaries'
    values:
      layout: bin